spring:
  application:
    name: contacts
  datasource:
    url: jdbc:mysql://localhost:3306/contacts?createDatabaseIfNotExist=true
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect